# Generated by Django 2.0.4 on 2018-04-12 12:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64)),
                ('bio', models.TextField()),
                ('organisation', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('github_login', models.CharField(max_length=32)),
                ('github_url', models.URLField()),
                ('twitter_url', models.URLField()),
                ('website_url', models.URLField()),
                ('avatar_url', models.URLField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('verbose_name', models.CharField(max_length=32)),
                ('order', models.IntegerField()),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.Type'),
        ),
    ]
