# Generated by Django 2.0.4 on 2018-04-12 13:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20180412_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
