# Generated by Django 2.0.4 on 2018-04-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20180412_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='github_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
