# Generated by Django 2.0.4 on 2018-04-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20180413_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'User Type'},
        ),
    ]
