# Generated by Django 2.0.6 on 2018-06-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20180613_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='news_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
