# Generated by Django 2.0.6 on 2018-06-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20180613_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='show_hireable',
            field=models.BooleanField(default=False),
        ),
    ]
