# Generated by Django 2.0.6 on 2018-06-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_person_show_hireable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='show_hireable',
            field=models.BooleanField(default=True),
        ),
    ]
