# Generated by Django 2.0.6 on 2018-06-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20180614_0946'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_active',
        ),
    ]
