# Generated by Django 2.0.6 on 2018-06-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_show_hireable_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='show_hireable',
        ),
        migrations.AddField(
            model_name='person',
            name='feature_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='job_opportunities',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='upcoming_events',
            field=models.BooleanField(default=True),
        ),
    ]
