# Generated by Django 2.0.6 on 2018-06-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_opt_in_splicing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='news_opt_in',
        ),
    ]
