# Generated by Django 2.0.4 on 2018-07-09 08:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_auto_20180628_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
